### PR TITLE
ENH: Use *NiWorkflows*' EPI-reference workflow

### PR DESCRIPTION
**Pull request by oesteban**
Replaces our workflows under ``dmriprep.workflows.dwi.util``.

### CODE REVIEW

**Comment by josephmje** [comment]
Thanks for this @oesteban! It looks like it should also fix the issues I had with some oblique datasets. Is the old `init_enhance_and_skullstrip_dwi_wf` also meant to be replaced with the `epi_mask` function from sdcflows?

**Comment by oesteban** [comment]
> Is the old `init_enhance_and_skullstrip_dwi_wf` also meant to be replaced with `init_brainextraction_wf` from sdcflows?

I think we should give it a try, at the very least.

**Review by josephmje — APPROVED** [review]
This looks good to me! It's going to fail because the eddy nodes are no longer corrected properly. I can make a followup PR that includes the new masking workflow.

**Comment by oesteban** [comment]
> This looks good to me! It's going to fail because the eddy nodes are no longer corrected properly.

I'll fix the connections tomorrow (my time). No need to break master for this.

**Comment by josephmje** [comment]
> I'll fix the connections tomorrow (my time). No need to break master for this.

Thanks @oesteban. I checked out the reference epi and I don't think it [looks like its supposed to](https://2543-174237413-gh.circle-artifacts.com/0/tmp/ds001771/derivatives/dmriprep/sub-36.html#acquisition-AP_datatype-figures_desc-brain_suffix-mask).

**Comment by oesteban** [comment]
ugh - I had fixed that already. I'll double-check that the pinned versions of sdcflows and niworkflows are being used.

**Comment by josephmje** [comment]
This is looking better. The JHU1 epiref still looks a little weird but I tested it locally and it was fine there. For the masking reportlet, we are currently showing the unwarped epiref and mask. But should we instead show the epiref and mask before unwarping? The warped mask would be the input to head motion correction.

**Pull request merged**
