### PR TITLE
ENH: Data-driven b0 identification tool

### PR DESCRIPTION
**Pull request by oesteban**
Extracted out from #29. There is a second portion of that one that should be considered in the context of the number of shells estimator.

### CODE REVIEW

**Comment by oesteban** [comment]
> Would it be possible to write a test for this with a multishell dataset where the B0s can often have variable gradient values (e.g. 0, 5, 10, 50)?

It would if the intent were to optimize the threshold of the algorithm to ensure it works with a dataset like that.
The proposal is testing just whether the manipulation of arrays is appropriate, dimensions, etc (i.e., formal parameters). And that is 100% more tests there were before...

Happy to take more tests in on a separate PR, with more scientific content as you suggest.

**Comment by dPys** [comment]
> > Would it be possible to write a test for this with a multishell dataset where the B0s can often have variable gradient values (e.g. 0, 5, 10, 50)?
> 
> It would if the intent were to optimize the threshold of the algorithm to ensure it works with a dataset like that.
> The proposal is testing just whether the manipulation of arrays is appropriate, dimensions, etc (i.e., formal parameters). And that is 100% more tests there were before...
> 
> Happy to take more tests in on a separate PR, with more scientific content as you suggest.

"And that is 100% more tests there were before..."
Very true. 

What about a case where there are nearly as many B0's as DWI volumes? Would be very unusual to encounter this, but it's certainly possible and could skew a purely z-score-based identification?

**Comment by oesteban** [comment]
> but it's certainly possible and could skew a purely z-score-based identification?

I'd say that's certain. I'm just rescuing your valuable code here :D - I think this function can be useful to flag anomalies. That is to say, some false positives may be allowable.

**Comment by oesteban** [comment]
I'll go ahead and merge this as a base for future developments. I feel it is more important to get @dPys' work merged even if the code is not deeply vetted than sticking with rigorous code review and perhaps block progress, at this point of the project.

**Pull request merged**
