### PR TITLE
MAINT: Increase minimal nibabel required version to 3.0.1

### PR DESCRIPTION
**Pull request by arokem**
I think that this should help resolve CI errors in #76,#77, #78, etc.

### CODE REVIEW

**Comment by josephmje** [comment]
our smriprep version also requires nibabel 3.0.0rc1. we may need to bump this up as well but i think there are changes to the way output spaces are handled in the new version.

**Comment by arokem** [comment]
Looks like I am getting some mysterious errors from nipype now. Anyone know these?

**Comment by oesteban** [comment]
I think @josephmje is right. Will bump smriprep before the meeting today.

**Comment by oesteban** [comment]
Solved via #83

**Pull request closed without merging**
