### PR TITLE
MAINT: A minimal infrastructure for unit-tests, with some initial test files

### PR DESCRIPTION
**Pull request by oesteban**
This PR adds a few files for basic testing, and sets-up pytest to run unit tests and doctests.

### CODE REVIEW

**Comment by arokem** [comment]
Good stuff! Where does that DWI data come from?

**Comment by oesteban** [comment]
> Good stuff! Where does that DWI data come from?

```Python
import numpy as np
import nibabel as nb
aff = nb.load('real_dwi_file.nii.gz').affine
nii = nb.Nifti1Image(np.zeros((10, 10, 10), dtype='uint8'), aff, None)
nii.header.set_qform(aff, code=1)
nii.header.set_sform(aff, code=1)
nii.to_filename('dmriprep/data/tests/dwi.nii.gz')
```

**Comment by oesteban** [comment]
Basically, I'm just using it for the affine header, to check RASB <-> IJK bvec/bval

**Comment by oesteban** [comment]
Merging to give a base for @dPys in his vectors PR (#26)

**Pull request merged**
