### PR TITLE
REF: main workflow and utilities

### PR DESCRIPTION
**Pull request by dPys**
This is my attempt at slimming things down and consolidating. Others' WIPs can still be added back in, but I wanted to PR something bare-bones to start.

### CODE REVIEW

**Comment by dPys** [comment]
graph

(basically this as a skeleton with the additional goals of adding support for multishell, and optional sdc via SyNb0, fieldmap, and topup--which we already have the utilities to support).

**Comment by arokem** [comment]
> I'm wondering whether the best thing to do would be to vchat at some point soon to figure out how best to merge together what everyone wants in dmriprep? My sense is that things are already getting fairly messy. I wish there was a way for us to work out these kinks in person (e.g. a minihack of sorts)

+1

1. Would be good to chat on a video conference sometime soon. Maybe we can schedule something for the week of September 23rd? If folks could indicate their availability [here](https://www.when2meet.com/?8108971-Y8OeY) we can get something on the calendar.

2. Who might be interested in coming to Seattle sometime in the next few months to work on this together? I can host at eScience, and can potentially provide travel support.

**Comment by oesteban** [comment]
Just entered my availability.

**Comment by dPys** [comment]
Entered my availability as well. 

I'd also be willing to hack with you all in Seattle provided that folks are available and travel funds might be available.

Cheers,
@dPys

**Comment by dPys** [comment]
@FYI: in advance of our meeting next week, the latest version of my fork of the repo has been updated considerably (also, the current has been rebased). Cli has also been set up, and stripped down to minimal inputs to get the pipeline to run. It can now also handle multiple sessions and multiple runs within session (which get automatically concatenated). 

From commandline, a single subject call across 3 separate sessions might look like the following:
`dmriprep /Users/derekpisner/Downloads/HNU1 /Users/derekpisner/Downloads/HNU1_output participant --participant_label 0025427 -s 1 2 3`

Also, a few more tweaks in light of some recent reading on order of operations with dmri preprocessing:
*denoising/gibbs correction moved near the beginning of the workflow (following motion outlier detection)
*N4BiasFieldCorrection added to end of the workflow to deal with brightness inhomogeneities

Look forward to conversing more next week.

Cheers,
@dPys

**Comment by dPys** [comment]
Latest wf (estimates sigma on the raw data, but save it for post-interpolation (i.e. eddy) to use for denoising):
graph

**Comment by dPys** [comment]
# TODO: Reduce size of Docker image (currently huge) by removing fslpy stuff from the 6.0.1 source install.

**Comment by oesteban** [comment]
Hey @dPys, do you think you'd be able to split this PR in more targeted, modular PRs? I can help with the git part if you want.

**Comment by dPys** [comment]
Yep, I had a feeling that would probably need to happen. Just FYI, this will produce a ton of PR's (you can probably tell this from the commit history within this PR).

What do you think about the following approach:
1) PR simple directory-structure cleanup as @josephmje began to do and I followed-up on.
2) PR updated set of config files that I've put together.
3) Start with submitting basic utilities and miscellaneous functions (i.e. found in utils/core.py, utils/bids.py, and utils/qc.py as I've currently organized them within this existing PR). This would also be a good opportunity to add docstring as well. It would be nice if we could find volunteers to write unit tests for each. These could be submitted as separate PR's by module?
4) Add any custom nipype interfaces (e.g. extended_eddy found in fsl_extensions.py in the present PR)
5) Add workflow structure to workflows/dwi (in the current PR, everything lives in base.py). This part I could see you and others wanting to modularize with subworkflow calls as previously discussed.
6) Integrate the bare-bones cli refactoring that I've done with more of the features offered from fmriprep.

It would be great if you could handle the git part? Let me know what you think about the above strategy and how you think it would be best to go about this.

@dPys

**Comment by oesteban** [comment]
Sounds great!

For most the git part, I believe it could be done with simple `git checkout nipreps -- file/to/cherry-pick` calls, so long you don't delete (intendedly or by mistake) your `nipreps` branch.

**Comment by dPys** [comment]
Great @oesteban , that sounds like a plan then. Will be careful to keep my nipreps branch alive.

Would you be able to demo an example of what you have in mind so that I can be sure we're on the same page with the plan of attack here?

Cheers,
@dPys

**Comment by arokem** [comment]
Hey @dPys : what of all this (if anything) is still relevant. Looks like a lot of the commits are coming from elswhere? We can look at cherry picking tomorrow, if that's still something we need to do.

**Comment by dPys** [comment]
Hi @arokem -- let's go ahead and close this PR since most of this is either being incorporated through separate PR's already or will be!

**Comment by arokem** [comment]
Okidoke!

**Pull request closed without merging**
