### PR TITLE
ENH: Set up customized report specification

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by oesteban** [comment]
Great work @josephmje on this one!. I'll merge as soon as we get a new release of niworkflows (that's the reason for the one test failing).

**Comment by josephmje** [comment]
> Great work @josephmje on this one!. I'll merge as soon as we get a new release of niworkflows (that's the reason for the one test failing).

I was just about to ask whether I should be concerned by the failed test. But looks like the anatomical workflows run now!

**Comment by josephmje** [comment]
With the new version of niworkflows, it looks like `BIDSDataGrabberOutputSpec` has changed to `_BIDSDataGrabberOutputSpec` in `dmriprep/interfaces/__init__.py`

**Comment by oesteban** [comment]
Okay, this seems to be working okay and the integration also works fine in fMRIPrep land - I'm going for it.

**Pull request merged**
